### ISSUE TITLE
xx.png.xxx.etc2.stex  cannot recover to png file

### ISSUE THREAD

**Issue by the3rduniverse** [bruvzg/gdsdecomp#132] opened 2023-05-11 08:08 UTC
### System information

win10 3060nv

### Issue description

xx.png.xxx.etc2.stex  cannot recover to png file

### Recovery log

USER ERROR: Condition "source_image->is_compressed()" is true. Returning: FAILED
   at: PNGDriverCommon::image_to_png (drivers\png\png_driver_common.cpp:134)
USER ERROR: Can't convert image to PNG.
   at: ResourceSaverPNG::save_image (drivers\png\resource_saver_png.cpp:54)
USER ERROR: Transient parent has another exclusive child.
   at: Window::set_visible (scene\main\window.cpp:747)

**Comment by nikitalita** [comment] 2023-05-11 22:09
I need the full recovery log for this; this is likely the [same issue here](https://github.com/bruvzg/gdsdecomp/issues/110#issuecomment-1373377663), but I need the full log to be sure.

**Comment by the3rduniverse** [comment] 2023-05-11 22:52
Here it is , I use gui tool to convert it 
```
****
Godot RE Tools, v0.5.3
****

-2023-05-12-06-50-51 [Convert textures]: converting F:/xxxx/cloud.png-27038f83399856800610d87294a3a590.etc2.stex
USER ERROR: Transient parent has another exclusive child.
   at: Window::set_visible (scene\main\window.cpp:747)
-2023-05-12-06-50-51 [Convert textures]: 
-2023-05-12-06-50-51       F:/xxxx/cloud.png-27038f83399856800610d87294a3a590.etc2.stex (write error)
-2023-05-12-06-50-51       
-2023-05-12-06-50-51 [Convert textures]: At least one error was detected!
USER ERROR: Condition "source_image->is_compressed()" is true. Returning: FAILED
   at: PNGDriverCommon::image_to_png (drivers\png\png_driver_common.cpp:134)
USER ERROR: Can't convert image to PNG.
   at: ResourceSaverPNG::save_image (drivers\png\resource_saver_png.cpp:54)
USER ERROR: Transient parent has another exclusive child.
   at: Window::set_visible (scene\main\window.cpp:747)
```

**Comment by nikitalita** [comment] 2023-05-15 00:19
Can you please upload the texture here so I can take a look?

**Comment by the3rduniverse** [comment] 2023-05-18 00:40
[cloud.png-27038f83399856800610d87294a3a590.etc2.stex.LOG](https://github.com/bruvzg/gdsdecomp/files/11503330/cloud.png-27038f83399856800610d87294a3a590.etc2.stex.LOG)

**Comment by the3rduniverse** [comment] 2023-05-18 00:42
I have modified the suffix name and I am not sure if the data was lost when uploading

**Comment by the3rduniverse** [comment] 2023-05-18 00:42
![cloud png-27038f83399856800610d87294a3a590 etc2 stex](https://github.com/bruvzg/gdsdecomp/assets/110324771/6f5dff54-5d9b-4c26-97aa-f18d941f871c)

**Comment by the3rduniverse** [comment] 2023-05-18 00:43
A png suffix was also uploaded

**Comment by nikitalita** [comment] 2023-05-27 19:26
yeah it's just in a format we can't decompress yet. This is a duplicate of #110

**Closed by nikitalita** 2023-05-27 19:26 UTC
Labels: bug
