### ISSUE TITLE
Extremely small UI for Mac

### ISSUE THREAD

**Issue by chaeyan** [bruvzg/gdsdecomp#155] opened 2023-12-13 21:53 UTC
### System information

MacBook Air M2 on Sonoma 14.1.1 (23B81)

### Issue description

the UI is extremely small, i can barely read things
<img width="1470" alt="Screenshot 2023-12-14 00 52 30" src="https://github.com/bruvzg/gdsdecomp/assets/32681723/166e1338-6239-4ad6-80a4-6ebd19665a20">

### Recovery log

N/A

**Comment by nikitalita** [comment] 2023-12-14 13:52
duplicate of #138

**Closed by nikitalita** 2023-12-14 13:52 UTC
Labels: bug
