### ISSUE TITLE
Cannot decompile Unrailed 2 Back on Track - Playtest

### ISSUE THREAD

**Issue by Aruvelut-123** [bruvzg/gdsdecomp#184] opened 2024-09-30 10:54 UTC
### System information

Windows 11 build 27686, AMD Radeon RX 6600

### Issue description

I have the game that i said and i tried to decompile it.
And it shows normal on the gdre tool.
But when i import it into godot editor, every .cs script are empty.
Please help.

### Steps to reproduce

1. Open GDRE tool
2. Select Unrailed2.pck and decompile it
3. Import it into godot 4.3 mono version because it's compile on that version (not custom engine)
4. Check any .cs script in the project

### Recovery log

GDRE Tools v0.6.2-52-g354b34
Windows 10.0.27686, AMD Radeon RX 6600, opengl3
Extracted 79 files, no errors detected!
WARNING: Converting lossy imports, you may lose fidelity for indicated assets when re-importing upon loading the project
   at: ImportExporter::_export_imports (modules\gdsdecomp\utility\import_exporter.cpp:65)
Script version 4.3.0 (rev 0x77af6ca) detected
Saved project config project.godot.
Saved project config project.godot.

********************************EXPORT REPORT********************************

Totals:                                 
Decompiled scripts:                     1
Failed scripts:                         0
Imported resources for export session:  79
Successfully converted:                 1
Lossy:                                  0
Rewrote metadata:                       0
Non-importable conversions:             0
Not converted:                          0
Failed conversions:                     0
-------------

------------------------------------------------------------------------------------

Use Godot editor version 4.3.0 to edit the project.
Note: the project may be using a custom version of Godot. Detection for this has not been implemented yet.
If you find that you have many non-import errors upon opening the project 
(i.e. scripts or shaders have many errors), use the original game's binary as the export template.

*******************************************************************************

### Minimal reproduction project

It cannot give out public (at least thats what i thought)
If you want please email me at 2502474438@qq.com
I will check email.
Btw, i'm chinese, so if i didn't reply on you that may because it's evening at our side.

**Comment by nikitalita** [comment] 2024-09-30 11:12
Duplicate of https://github.com/bruvzg/gdsdecomp/issues/67

**Closed by nikitalita** 2024-09-30 11:12 UTC
Labels: bug
