### ISSUE TITLE
Support Godot version 4.3

### ISSUE THREAD

**Issue by Svenskithesource** [bruvzg/gdsdecomp#179] opened 2024-08-04 16:54 UTC
### Describe the problem or limitation you are having

The project does not compile when added to the modules for Godot version 4.3. There are numerous errors that occur when trying to compile, which is expected if the project is not designed to compile for this.

### Describe the feature / enhancement and how it helps to overcome the problem or limitation

It will allow us to use the tool for games compiled with Godot v4.3.

**Comment by nikitalita** [comment] 2024-08-04 22:48
duplicate of https://github.com/bruvzg/gdsdecomp/issues/172

**Closed by nikitalita** 2024-08-04 22:48 UTC
Labels: enhancement
